added author: Mia Gomez
halperta/criticalarchives pull request #14
Opened 2018-10-11 04:46 UTC by miag2193

Adding author ID for Mia Gomez

2018-10-13 14:00 UTC, halperta requested changes
Mia - this is a well-written, clear, and comprehensive discussion of the Mexico Project, and very close to complete. I've met Kate Doyle a few times and really admire the work that the NSA is doing. Kate is amazing.

I have requested a few revisions related to formatting, and made one recommendation related to the conclusion.

Please submit revisions by next Saturday, Oct 20. Don't hesitate to write with any questions.
Hannah

2018-10-13 14:00 UTC, halperta commented on _posts/blog/2018-10-10-Mexico-Project.md
> +The Mexico Project is a digital resource organized under the National Security Archive (https://nsarchive.gwu.edu/) consisting of primary source documents from government agencies in both the United
Because the name "national security archive" can be confusing, you might briefly explain that it's an independent org (i.e. not run by the government).

2018-10-13 14:00 UTC, halperta commented on _posts/blog/2018-10-10-Mexico-Project.md
> +The Mexico Project can be accessed under the “Projects” drop-down menu on the National Security Archive’s home page (https://nsarchive.gwu.edu/). Users are redirected to the project’s main page where
Use markup to turn all the URL's into links. Put the text you want to link brackets, and the url immediately after in parentheses. You can find more info: http://www.halperta.com/criticalarchives/tutorial/writing-in-markdown/

2018-10-13 14:00 UTC, halperta commented on _posts/blog/2018-10-10-Mexico-Project.md
> +https://nsarchive.gwu.edu/project/mexico-project , Accessed October 2, 2018.
At the very top of this document, you'll need to use a YAML heading: http://www.halperta.com/criticalarchives/tutorial/writing-in-markdown/

2018-10-13 14:00 UTC, halperta commented on _posts/blog/2018-10-10-Mexico-Project.md
> +The Mexico Project’s chief aim is to disseminate information to the public and to make declassified documents increasingly available in Mexico. With over 1,600 Freedom of Information requests having
Use markdown to italicize "Paper Cadavers"

2018-10-13 14:00 UTC, halperta commented on _posts/blog/2018-10-10-Mexico-Project.md
> +With that being said, the biggest drawback with the project’s website is its lack of updated material. A three-year gap exists between the most recent story, having been published on October 2, 2018,
Consider framing this as an opportunity, rather than a drawback. There are often compelling reasons why a project hasn't been updated, like lack of funding, or other pressing projects. It might be more useful to think about what scholars can do to fill in the gap (i.e. "scholars should consult this resource alongside other sources such as...") or as an opportunity for new projects (i.e. "since this project seems to have lapsed, there is a need for others to fill in the gaps by...").

2018-10-17 20:24 UTC, miag2193 commented on _posts/blog/2018-10-10-Mexico-Project.md
> +https://nsarchive.gwu.edu/project/mexico-project , Accessed October 2, 2018.
Okay! I'll add that now.

2018-10-17 20:24 UTC, miag2193 commented on _posts/blog/2018-10-10-Mexico-Project.md
> +The Mexico Project is a digital resource organized under the National Security Archive (https://nsarchive.gwu.edu/) consisting of primary source documents from government agencies in both the United
I'll clear that up in the first sentence.

2018-10-17 20:25 UTC, miag2193 commented on _posts/blog/2018-10-10-Mexico-Project.md
> +The Mexico Project can be accessed under the “Projects” drop-down menu on the National Security Archive’s home page (https://nsarchive.gwu.edu/). Users are redirected to the project’s main page where
I thought that I had done this the night of when I submitted the review. In fact, when I go in to edit I can see that there are italics and links submitted properly, so I'm not sure why you can't see that.

2018-10-17 20:26 UTC, miag2193 commented on _posts/blog/2018-10-10-Mexico-Project.md
> +With that being said, the biggest drawback with the project’s website is its lack of updated material. A three-year gap exists between the most recent story, having been published on October 2, 2018,
I like that perspective a lot better, and I didn't think of it that way. Thank you!

2018-10-17 20:27 UTC, miag2193 commented on _posts/blog/2018-10-10-Mexico-Project.md
> +The Mexico Project’s chief aim is to disseminate information to the public and to make declassified documents increasingly available in Mexico. With over 1,600 Freedom of Information requests having
Again, I thought that I had done this already. When I made changes to the format last week and I went to make another pull request it never gave me the option. I tried several times, but I couldn't complete it.

2018-10-19 19:42 UTC, halperta approved these changes

2018-10-19 19:42 UTC, merged