Adding profile for new student
halperta/criticalarchives pull request #16
Opened 2018-10-17 15:29 UTC by jessisanch12

2018-10-19 01:38 UTC, jessisanch12 commented
Submitting Review for Ticha

2018-10-22 15:35 UTC, halperta requested changes
Jessica - Ticha is one of my favorite projects, and I'm really glad to see you reviewing it here. I really like how you address the question of access and community-centered digital humanities at the end. 

I've added some recommendations to improve the clarity of the prose, and requested that you reformat it using markdown (instructions below). Please submit your revisions by next Monday, October 29.

2018-10-22 15:35 UTC, halperta commented on 2018-10-25-Ticha-Review
> +Lillehaugen, Brook Danielle, George Aaron Broadwell, Michel R. Oudijk, & Laurie Allen. 2015.
Please format this article using Markdown. This includes using simple codes to italicize or bold titles, adding links, and adding a YAML header. The instructions are here:

http://www.halperta.com/criticalarchives/tutorial/writing-in-markdown/

2018-10-22 15:35 UTC, halperta commented on 2018-10-25-Ticha-Review
> +Ticha means language in Zapotec, an indigenous language spoken in Southern Mexico. Thicha is a digital platform
Typo: "thicha" in second sentence.

2018-10-22 15:35 UTC, halperta commented on 2018-10-25-Ticha-Review
> +Ticha analyzes data through two main technological platforms: FLEx which is Fieldworks Language Explorer, a system for
This sentence is a little confusing - it's unclear what the two platforms are. Perhaps break it into two sentences? I might use a different word in terms of platform. Perhaps "Ticha encodes the data in two ways:"

2018-10-22 15:35 UTC, halperta commented on 2018-10-25-Ticha-Review
> +the about page, there are videos about the project with the team.
Think about reorganizing the information in this paragraph in terms of priority. I see three main descriptive points: the topic of the collection, the content of the collection, and the encoding system. I would organize them so the topic comes first, followed by content, and finally encoding.

2018-10-22 15:35 UTC, halperta commented on 2018-10-25-Ticha-Review
> +The Colonial Zapotec section includes a linguistic background and cultural context to situate the project in contemporary
Please add links to these pages.

2018-10-22 15:35 UTC, halperta commented on 2018-10-25-Ticha-Review
> +a community that has been silenced. Therefore, as the digital archive develops and expands, how will Ticha continue to
Either rewrite this final sentence as a statement, or end with a question mark.

2018-11-02 01:25 UTC, halperta requested changes
Jessica - this is so close to complete! There are just a few typos and small grammatical corrections left. I've marked them all, using italics to show recommended changes, or if it's a typo just writing the word in question. Once that's done, we can publish!

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +Ticha is an innovative and interactive contemporary digital platform that bring awareness to the users. Each of the
* brings

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +sections contextualize the project and explore the texts section, provides a wide range of materials. For instance,
* providing

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +twenty one found in Spanish and twenty-nine in Zapotec, all are organized by name, year, town, archive, type of document
"all organized by"

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +Zapotec and Spanish, transcriptions in Zapotec and in Spanish with the following metadata: archive name, collection, call
* Zapotec and Spanish, _as well as_ transcriptions in ...

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +studies and anyone who is interested about colonial Zapotec. This platform was also created for the one and half million
* interested _in_ colonial Zapotec

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +Putman states, “the impact of digitization on the knowability of past processes of whatever scale and locale is significant”
* putnam

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +reflect several voices in the archive, and continue to emphasize a sense of reciprocity to the Zapotec community?
* reciprocity _with_ the Zapotec community.

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +The corpus presented is from the colonial period which focus on three main works, all of these texts come from the
from the colonial period _and focuses on_ three main works;

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +geographic region of Central Valley Zapotec Oaxaca. The first one is [Arte], a book published in 1578 by Juan de
Please italicize the titles. You can do this by adding a * on each side of the word or phrase (with no spaces in between)

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +by Dominican priest Pedro de Feria. The third set of meterials presented are handwritten texts mainly written by native
* materials

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +(https://ticha.haverford.edu/en/about/). A opportunity that allows users to understand the motivation and processes of
* _This opportunity allows_ users to understand...

2018-11-02 01:25 UTC, halperta commented on 2018-10-25-Ticha-Review
> +therefore its not surprising that Ticha encodes the data in the following two ways: FLEx which is Fieldworks Language
therefore _it's_ not surprising

2018-11-02 18:25 UTC, merged